name: Publish npm
on:
  release:
    types: published
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build-napi-rs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: x86_64-apple-darwin, os: macos-latest }
          - { target: aarch64-apple-darwin, os: macos-latest }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: rustup toolchain install stable -t "$TARGET"
        shell: bash
        env:
          TARGET: ${{ matrix.target }}
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
      - if: matrix.os == 'macos-latest'
        run: curl -sS https://webi.sh/zig | sh
      - run: npm ci
      - run: npx napi build --platform --release --target "$TARGET"
        shell: bash
        env:
          TARGET: ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            index.js
            index.d.ts
            *.node
  publish-npm:
    needs: build-napi-rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - run: npm ci
      - run: mv artifacts/*/index*.node .
      - run: mv artifacts/x86_64-unknown-linux-gnu/index.* .
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
